#!/bin/bash

# Check to make sure /var/lib/mysql is present
if [ ! -d /var/lib/mysql ]; then
  echo "/var/lib/mysql is not present!"
  echo "Make sure you map the host directory to the container"
  exit 1
fi

# Copy the configuration file.
if [ -e /var/lib/mysql/my.cnf ]; then
  echo "Copying configuration..."
  cp -v /var/lib/mysql/my.cnf /etc/my.cnf
fi

# Run any preconfig script if present
if [ -e /var/lib/mysql/script.pre ]; then
  /var/lib/mysql/script.pre
fi

# Run MariaDB
echo "Starting MariaDB..."
/usr/lib/mysql/mysql-systemd-helper install   default
/usr/lib/mysql/mysql-systemd-helper upgrade   default
/usr/lib/mysql/mysql-systemd-helper start     default &
MYSQL_PID=$!
/usr/lib/mysql/mysql-systemd-helper wait      default

echo $MYSQL_PID > /run/watch/mariadb

